<script lang="ts">
	import {
		Sparkles,
		Sprout,
		Network,
		MessagesSquare,
		Palette,
		Blocks,
		Orbit,
		Bot,
		Wrench,
		BookOpen,
		Workflow,
		Compass,
		House,
		Route,
		FlaskConical,
		Mic,
		Library,
		FolderOpen,
		ChartNoAxesCombined,
		Search,
		ArrowRight,
		ArrowUpRight,
		ChevronRight,
		ChevronLeft,
		Check,
		X,
		Menu,
		Clock,
		Bookmark,
		CircleHelp,
		GraduationCap,
		ExternalLink,
		Download,
		RotateCcw,
		Lightbulb,
		ShieldCheck,
		Play,
		CircleCheck,
		Coffee,
		Heart,
		ArrowLeft,
		FileText,
		ListChecks,
		ChevronDown,
		Target,
		Layers,
		Calculator,
		Zap,
		Pause
	} from '@lucide/svelte';
	const icons = {
		sparkles: Sparkles,
		sprout: Sprout,
		network: Network,
		messages: MessagesSquare,
		palette: Palette,
		blocks: Blocks,
		orbit: Orbit,
		bot: Bot,
		wrench: Wrench,
		book: BookOpen,
		workflow: Workflow,
		compass: Compass,
		home: House,
		route: Route,
		flask: FlaskConical,
		mic: Mic,
		library: Library,
		folder: FolderOpen,
		chart: ChartNoAxesCombined,
		search: Search,
		arrow: ArrowRight,
		upRight: ArrowUpRight,
		right: ChevronRight,
		left: ChevronLeft,
		check: Check,
		x: X,
		menu: Menu,
		clock: Clock,
		bookmark: Bookmark,
		help: CircleHelp,
		graduation: GraduationCap,
		external: ExternalLink,
		download: Download,
		reset: RotateCcw,
		bulb: Lightbulb,
		shield: ShieldCheck,
		play: Play,
		circleCheck: CircleCheck,
		coffee: Coffee,
		heart: Heart,
		back: ArrowLeft,
		file: FileText,
		list: ListChecks,
		down: ChevronDown,
		target: Target,
		layers: Layers,
		calculator: Calculator,
		zap: Zap,
		pause: Pause
	};
	let {
		name,
		size = 20,
		stroke = 1.7,
		class: className = ''
	}: { name: string; size?: number; stroke?: number; class?: string } = $props();
	const Component = $derived(icons[name as keyof typeof icons] ?? Sparkles);
</script>

<Component {size} strokeWidth={stroke} class={className} aria-hidden="true" />
